version: '3'

services:
  oracledb:
    image: mokowmy/oracle11g_moko:oracle11g_moko_ver1
    restart: always
    ports: 
      - "1521:1521"

  php7-with-oci8:
    depends_on:
      - oracledb
    image: adrianharabula/php7-with-oci8:7.1.16-apache-jessie-oci-2.1.8-instantclient-12.2.0.1.0
    links: 
      - oracledb
    volumes:
      - ./src:/var/www/html
    ports:
      - 8080:80

volumes:
  src: